version: '3.1'

services:

  db:
    restart: always
    build:
      context: ./Docker
      dockerfile: Dockerfile
    ports:
      - 5432:5432    

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
    ports:
        - "8080:80"      